
version: 3.0
services:
# nginx server to host frontend application
  web:
    build: 
      context: web-app
      dockerfile: Dockerfile.frontend
      target: 
    networks:
      - app_network
    ports:
      - "8080:80"

# Express server
  app:
    build: .
    environment:
      - PROCESS_MODE=cluster
    ports:
      - 
  localstack:
    ports:
      - "4566:4566"
    environment:
      - EDGE_PORT=4566
      - SERVICES=dynamodb
    networks:
      - app_network
  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    networks:
      - app_network
networks:
  app_network:
